### ISSUE TITLE
How can I get compiled version without bower?

### ISSUE THREAD

**Issue by SatheesA** [cbcrc/koco-router#4]

**Comment by RCMax** [comment]
There is no compiled version yet. 

Even if this router could be use in any project, it is mainly created for the [koco "framework"](https://github.com/cbcrc/generator-koco)

The compilation is part of the [koco "framework"](https://github.com/cbcrc/generator-koco)

**Comment by SatheesA** [comment]
Ah okey, thats to bad. I just needed a router and this looked interesting

**Comment by RCMax** [comment]
You can use this router without using [koco "framework"](https://github.com/cbcrc/generator-koco) but you will have to configure requirejs and plug-in the dependencies : jquery, knockout-utilities, knockout, lodash, byroads.
